name: Security report
description: Report a potential security vulnerability affecting the project.
title: "[Security]: "
labels:
  - security
body:
  - type: markdown
    attributes:
      value: |
        For sensitive vulnerabilities, use the private process in `SECURITY.md`.
        If this issue is submitted publicly, avoid posting exploit payloads or secrets.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - local (docker-compose)
        - dev
        - staging
        - production
    validations:
      required: true

  - type: textarea
    id: affected_surface
    attributes:
      label: Affected surface
      description: Which area is impacted?
      placeholder: |
        - upload ZIP pipeline
        - /api auth/JWT
        - leaderboard submit
        - analytics event
        - /games MinIO exposure
        - nginx proxy/CORS/CSP
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide minimal reproducible steps.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected secure behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual insecure behavior
    validations:
      required: true

  - type: input
    id: request_id
    attributes:
      label: request_id (if available)
      description: Include response request IDs from failing API requests.

  - type: textarea
    id: logs
    attributes:
      label: Logs / evidence
      description: Include sanitized logs, traces, and proof-of-concept output.
      render: shell

  - type: textarea
    id: impact
    attributes:
      label: Impact assessment
      description: Confidentiality, integrity, availability impact and exploitability.
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested mitigation
      description: Optional immediate guardrails or patch direction.
